### ISSUE TITLE
authClient error after updating to 0.30 or higher

### ISSUE THREAD

**Issue by richardkazuomiller** [GoogleCloudPlatform/gcloud-node#1355]
After updating gcloud I get this error that crashes the process when trying to make any requests to datastore on v0.34.0

````
/Users/richardkazuomiller/Sites/feedproxy/node_modules/gcloud/lib/common/grpc-service.js:430
  this.authClient.getAuthClient(function(err, authClient) {
                  ^

TypeError: this.authClient.getAuthClient is not a function
    at Datastore.GrpcService.getGrpcCredentials_ (/Users/richardkazuomiller/Sites/feedproxy/node_modules/gcloud/lib/common/grpc-service.js:430:19)
    at Datastore.GrpcService.request (/Users/richardkazuomiller/Sites/feedproxy/node_modules/gcloud/lib/common/grpc-service.js:218:10)
    at DatastoreRequest.request_ (/Users/richardkazuomiller/Sites/feedproxy/node_modules/gcloud/lib/datastore/request.js:885:8)
    at DatastoreRequest.get (/Users/richardkazuomiller/Sites/feedproxy/node_modules/gcloud/lib/datastore/request.js:348:8)
    at DatastoreRequest.get (/Users/richardkazuomiller/Sites/feedproxy/node_modules/gcloud/lib/datastore/request.js:292:10)
    at Object.<anonymous> (/Users/richardkazuomiller/Sites/feedproxy/lib/dataset.js:9:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
````

This is my code

````
const options = {
  projectId: <my-project-id>,
  keyFilename: <my-key-json>
}
const gcloud = require('gcloud')(options)
const datastore = gcloud.datastore()

const key = datastore.key(['Foo','bar'])

datastore.get(key,function(err,entity){
  console.log('foo',err,entity)
})

module.exports = datastore
````

The same code, other than changing `datastore.dataset()` to `datastore()` works on v0.29. Am I doing something wrong or is this a bug?

**Comment by stephenplusplus** [comment]
Sounds like it could be an issue when switching between versions without fully un- and re-installing all npm dependencies. After installing gcloud@0.34.0, try a `rm -rf node_modules && npm install`.

**Comment by richardkazuomiller** [comment]
That did it, which probably means that there's a dependency whose version needs to be updated in the dependencies configuration.

**Comment by stephenplusplus** [comment]
Thanks for reporting!

**Comment by richardkazuomiller** [comment]
@stephenplusplus You're quick! I was just writing about how I found that running with `google-auto-auth@0.2.3` was what caused it lol. Thanks for the fix.

**Comment by stephenplusplus** [comment]
Haha, only thanks to you for sending me in the right direction 😄
